# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.box = "generic/debian10"
  # config.vm.define "all-sites" 
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "private_network", ip: "192.168.58.10"
    config.vm.synced_folder "../1/tmp_files", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
   vb.name = "all-vhost"
   vb.gui = false
   vb.memory = "512"
    end
  config.vm.provision "shell", inline: <<-SHELL
        apt-get upgrade
        apt-get install -y apache2
        apt-get install -y php
        mkdir -p /var/www/html/
        cp -rf /vagrant/index.html /var/www/html/index.html
        mkdir -p /var/www/php/
        cp -rf /vagrant/index.php /var/www/php/index.php
        cp -rf /vagrant/all_vhost.conf /etc/apache2/sites-available/all_vhost.conf
        sudo a2ensite all_vhost.conf
        systemctl reload apache2.service
    SHELL
    
end

