---
- name: Jenkins
  hosts: jenkins.vm
  tasks:
  roles:
    - role: Jenkins
  become: true
   
- name: Nexus
  hosts: nexus.vm
  become: true

  vars:
    nexus_admin_password: "admin"
    nexus_public_hostname: 'nexus.vm'
    httpd_setup_enable: false
    nexus_upgrade: true
        
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit

    nexus_local_users:
      - username: jenkins # used as key to update
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        password: "jenkins"
        roles:
          - Developpers # role ID here

  roles:
    - role: geerlingguy.java

  #  - role: nexus3-oss