---
- hosts: 
   - static
  vars:
    vhost_p: "8000"
    dir_vhost: "/var/www/html"
  tasks:
  - name: install Apache
    become: true 
    apt:
      name: apache2
      state: present
  - name: copy file index.html with owner and permissions
    become: true
    copy:   
      src: /vagrant/files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0755
      remote_src: true
  - name: change Apache port is 8000
    become: true
    lineinfile:
      dest: /etc/apache2/ports.conf
      regexp: '^Listen 80' 
      line: Listen 8000
      state: present

  - name: vhost configure
    become: true
    template:
        src: vhost_conf.j2
        dest: /etc/apache2/sites-available/vhost.conf

  - name: a2ensite enabled
    become: true
    command: /usr/sbin/a2ensite vhost.conf
    
  - name: restart apache2
    become: true
    service:
        name: apache2
        state: reloaded