# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.box = "generic/debian10"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.define "2host"
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
   vb.name = "2vhost-ans_conf"
   vb.gui = false
   vb.memory = "512"
    end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.limit = 'all'
    ansible.inventory_path = "inventory"

    end


    
end
