# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "generic/debian10"
    
  config.vm.define "html" do |html|
    html.vm.provider "virtualbox" do |vb|
      vb.name = "html-host"
      vb.gui = false
      vb.memory = "512"
      end
    html.vm.network "private_network", ip: "192.168.58.11"
    html.vm.synced_folder "../1/tmp_files", "/vagrant"
    html.vm.provision "shell", inline: <<-SHELL
        apt-get upgrade
        apt-get install -y apache2
        cp -rf /tmp_files/vagrant/index.html /var/www/html/index.html
        systemctl reload apache2.service
    SHELL
   end
  config.vm.define "php" do |php|
    php.vm.provider "virtualbox" do |vb|
      vb.name = "php-host"
      vb.gui = false
      vb.memory = "512"
      end
    php.vm.network "private_network", ip: "192.168.58.12"
    php.vm.synced_folder "../1/tmp_files", "/vagrant"
    php.vm.provision "shell", inline: <<-SHELL
      apt-get upgrade
      apt-get install -y apache2
      apt-get install -y php
      mkdir -p /var/www/php/
      cp -rf /tmp_files/vagrant/index.php /var/www/php/index.php
      sed -i 's/html/php/g' /etc/apache2/sites-enabled/000-default.conf 
      systemctl reload apache2.service
    SHELL
  end
  
  
end
