apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: my-project
  source:
    repoURL: https://github.com/owl-sarge/devops-hometasks.git
    targetRevision: main
#    path: charts
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true