---
- name: Add an Apt signing key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add repository into sources list
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: install openjdk-17-jre, build-essential
  apt:
    name:
      - openjdk-17-jre
      - build-essential
    state: present

- name: Install jenkins
  apt:
    name: jenkins
    state: present
    update_cache: true

- name: Create scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Copy groovy scripts 
  copy: 
    src: /vagrant/roles/Jenkins/files/
    dest: "{{ jenkins_home }}/init.groovy.d/"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0755
    remote_src: true

- name: Jenkins service configure
  lineinfile:
    dest: /lib/systemd/system/jenkins.service
    regexp: '^Environment="JAVA_OPTS=-Djava.awt.headless=true"$'
    line: Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config=/var/lib/jenkins/casc_configs"
    state: present

- name: Change TimeoutStart
  lineinfile:
    dest: /lib/systemd/system/jenkins.service
    regexp: '^#TimeoutStartSec=90$'
    line: TimeoutStartSec=180
    state: present

- name: Create options directory
  file:
    path: "{{ jenkins_home }}/casc_configs"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Copy options file
  copy: 
    src: /vagrant/roles/Jenkins/templates/
    dest: "{{ jenkins_home }}/casc_configs"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0755
    remote_src: true    

- name: Copy jobs
  copy: 
    src: /vagrant/roles/Jenkins/templates/jobs/
    dest: "{{ jenkins_home }}/jobs/"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0755
    remote_src: true

- name: Restarted service Jenkins
  become: true
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: true