apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.container.label }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
