name: wcg build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout repo
      - uses: actions/checkuot@v4
        with:
          repository: ''

      - name: build image
        run: docker build -t wcg:multi -f Dockerfile.multi .
      
