name: wcg build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: build image
        run: docker build -t wcg -o wcg.tar -f 07-docker/Dockerfile.multi .
      
      - name: Archive image
        uses: actions/upload-artifact@v3
        with:
          name: wcg
          path: var/lib/docker/wcg

      - name: Test directory
        run: var/lib/docker/wcg ls -al
