name: Build wcg

env:
  REGISTRY: "ghcr.io"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
          
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v.1.0"
          message: "Latest release"
          
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
          
      - name: docker build and push
        env:
          image_tag: ${{ github.sha }}
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:$image_tag -t ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:latest -f 07-docker/Dockerfile.multi .
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:$image_tag
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:latest
 
