name: wcg build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout repo
      - uses: actions/checkout@v4
 #       with:
 #         repository: 'owl-sarge/devops-hometasks'

  #    - name: build image
  #      run: docker build -t wcg:multi -f Dockerfile.multi .
      
