name: wcg build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: checkout repo
        with:
          repository: ''

      - name: build image
        run: docker build -t wcg:multi -f Dockerfile.multi .
      
