name: wcg build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: build image
        run: docker build -t wcg:multi -f Dockerfile.multi .
      
