name: Build wcg

env:
  REGISTRY: "ghcr.io"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
          
      - name: docker build and push
        env:
          image_tag: ${{ steps.tag_version.outputs.new_tag }}
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:$image_tag -t ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:latest -f 07-docker/Dockerfile.multi .
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:$image_tag
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}/wcg:latest

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
  
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
  
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
  
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
 
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
  
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          pages_branch: main
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  
